### ISSUE TITLE
Not working if items are clickable

### ISSUE THREAD

**Issue by matecode** [fedorenkoalex/bottomsheetrecycler#1]
Hi! Thanks for your work, which seems to work great. But there is a problem: it is not working if items in RecyclerView are clickable.

Just add android:clickable="true" to ReleativeLayout of of item_list.xml

Then it is scrollable, but only if you manage to click outside the item (in your example case you must click between two items)

Any suggestions how to solve this problem? Thanks

**Comment by maxim-petlyuk** [comment]
I fixed this. You can try the solution in the pull-request
https://github.com/fedorenkoalex/bottomsheetrecycler/pull/2

**Comment by fedorenkoalex** [comment]
Hi @matecode .
Sorry that I did not reply for a while. Please check update in repository. With the help of @mpetlyuk this bug fixed now.
