### ISSUE TITLE
how use this in BottomSheetDialogFragment?

### ISSUE THREAD

**Issue by rasoulmiri** [fedorenkoalex/bottomsheetrecycler#3]
i need use this class extends from BottomSheetDialogFragment?

**Comment by fedorenkoalex** [comment]
Hi. Now this only for bottomsheet with views.
So i think to use this with BottomSheetDialog you need a source of it and use my class BottomSheetBehaviorv2 instead BottomSheetBehavior inside BottomSheet Dialog. 
Maybe it will work...
 I will add possibility to use this with BottomSheetDialog bit later(maybe on Monday). 

Thank you for report.

**Comment by rasoulmiri** [comment]
I'm waiting for you on Monday 👍

**Comment by fedorenkoalex** [comment]
Hi @rasoulmiri. I added some changes to code. 

Maybe this is not the most correct way to solve this problem, but it works.
You need add classes from .control package and design_bottom_sheet_fixed.xml to your project.
And you need to use BottomSheetDialogv2 instead BottomSheetDialog for creating bottomsheet dialog.  
More details can be found in MainActvitity.class (createDialogBtmSheet(); function).

**Comment by rasoulmiri** [comment]
Thank you very much, but it's very jumpy...
